import type { Vulnerability } from './Beacon/types';

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

function daysAgoTimestamp(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(9 + (days % 8), (days * 17) % 60, (days * 7) % 60);
  return d.toISOString().replace('T', ' ').substring(0, 16);
}

export const mockVulnerabilities: Vulnerability[] = [
  // CID-01 (batch-1)
  {
    uuid: 'v1',
    vulnerabilityId: 'LWL-2026-4401',
    purl: 'pkg:maven/org.apache.logging.log4j/log4j-core@2.17.1',
    componentName: 'log4j-core',
    componentVersion: '2.17.1',
    title: 'JNDI injection via crafted log message',
    cwe: 'CWE-917',
    description: 'Remote code execution through JNDI lookup in log messages',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Submitted',
    complexity: 'Extensive',
    submittedDate: daysAgo(2),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 2,
    embargo: true,
    duplicate: false,
    blocked: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v2',
    vulnerabilityId: 'LWL-2026-4301',
    purl: 'pkg:pypi/django@4.1.0',
    componentName: 'Django',
    componentVersion: '4.1.0',
    title: 'SQL injection in QuerySet.extra()',
    cwe: 'CWE-89',
    description: 'SQL injection through unsanitized extra() parameters',
    severity: 'Important',
    cvss: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    stage: 'Classified',
    complexity: 'Complex',
    submittedDate: daysAgo(7),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 7,
    embargo: false,
    duplicate: false,
    blocked: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v3',
    vulnerabilityId: 'LWL-2026-4101',
    purl: 'pkg:maven/org.apache.commons/commons-text@1.9',
    componentName: 'Apache Commons Text',
    componentVersion: '1.9',
    title: 'Text4Shell - StringSubstitutor interpolation',
    cwe: 'CWE-94',
    description: 'Code injection through uncontrolled string interpolation',
    severity: 'Moderate',
    cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    stage: 'Validation',
    complexity: 'Standard',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 35,
    embargo: false,
    duplicate: false,
    blocked: true,
    ltwlsupt_ticket_id: 'batch-1',
  },

  // CID-214 (batch-2)
  {
    uuid: 'v4',
    vulnerabilityId: 'LWL-2026-4201',
    purl: 'pkg:maven/org.apache.tomcat/tomcat-catalina@9.0.65',
    componentName: 'Tomcat Catalina',
    componentVersion: '9.0.65',
    title: 'Request smuggling via chunked encoding',
    cwe: 'CWE-444',
    description: 'HTTP request smuggling through malformed chunked transfer encoding',
    severity: 'Critical',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    stage: 'Fix in Progress',
    complexity: 'Extensive',
    submittedDate: daysAgo(15),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 15,
    embargo: true,
    duplicate: false,
    blocked: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v5',
    vulnerabilityId: 'LWL-2026-4001',
    purl: 'pkg:maven/org.apache.shiro/shiro-core@1.10.0',
    componentName: 'Apache Shiro',
    componentVersion: '1.10.0',
    title: 'Authentication bypass via path traversal',
    cwe: 'CWE-287',
    description: 'Auth bypass using path normalization inconsistencies',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    stage: 'Lightwell Network',
    complexity: 'Complex',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 35,
    embargo: false,
    duplicate: false,
    blocked: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v6',
    vulnerabilityId: 'LWL-2026-4404',
    purl: 'pkg:pypi/requests@2.28.0',
    componentName: 'requests',
    componentVersion: '2.28.0',
    title: 'SSRF via redirect handling',
    cwe: 'CWE-918',
    description: 'Server-side request forgery through unvalidated redirects',
    severity: 'Minor',
    cvss: 3.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    stage: 'Submitted',
    complexity: "Won't Fix",
    submittedDate: daysAgo(1),
    lastUpdated: daysAgoTimestamp(0),
    ageDays: 1,
    embargo: false,
    duplicate: true,
    blocked: false,
    duplicateOf: 'LWL-2026-4027',
    ltwlsupt_ticket_id: 'batch-2',
  },
];
